http://localhost:3000/ping

###

POST http://localhost:3000/ping
Content-Type: application/json

{
  "name": "Isabele"
}

### Get all class
GET http://localhost:3000/class

### Create Class
POST http://localhost:3000/class
Content-Type: application/json

{
  "name": "Cruz",
  "startDate": "2021-01-25",
  "endDate": "2021-07-31",
  "module": "8"
}

### All Students in Class By Name
GET http://localhost:3000/class/cruz

### All Students in Class By Name
GET http://localhost:3000/class/cruz/students

### All Teachers in Class By Name
GET http://localhost:3000/class/cruz/teachers

### Update Class
PUT http://localhost:3000/class/c3ceec33-29b2-40d3-8cc9-3d3f16da9c33
Content-Type: application/json

{
  "name": "Epis",
  "startDate": "2021-01-25",
  "endDate": "2021-07-31",
  "module": "8"
}

### Delete Class
DELETE http://localhost:3000/class/c3ceec33-29b2-40d3-8cc9-3d3f16da9c33