http://localhost:3000/api/ping

###

POST http://localhost:3000/api/ping
Content-Type: application/json

{
  "name": "Isabele"
}

### Get all class
GET http://localhost:3000/api/class

### Create Class
POST http://localhost:3000/api/class
Content-Type: application/json

{
  "name": "Cruz",
  "startDate": "2021-01-25",
  "endDate": "2021-07-31",
  "module": "8"
}

### Update Class
PUT http://localhost:3000/api/class/c3ceec33-29b2-40d3-8cc9-3d3f16da9c33
Content-Type: application/json

{
  "name": "Epis",
  "startDate": "2021-01-25",
  "endDate": "2021-07-31",
  "module": "8"
}

### Delete Class
DELETE http://localhost:3000/api/class/94a0930c-a255-4051-9226-5b9f812c23fa
Content-Type: application/json

{
  "name": "Epis",
  "startDate": "2021-01-25",
  "endDate": "2021-07-31",
  "module": "8"
}


### Get all students
GET http://localhost:3000/api/student
### Get all Teachers
GET http://localhost:3000/api/teacher
### Get all Hobbies
GET http://localhost:3000/api/hobbies
### Get all Skills
GET http://localhost:3000/api/skills
### Get all TeacherSkills
GET http://localhost:3000/api/teacheSkills


### Get all studentsHobbies
GET http://localhost:3000/api/studentHobbies

### Create TeacherSkills
POST http://localhost:3000/api/teacheSkills
Content-Type: application/json

  {
    "teacher_id": "ddd03ba5-f425-41da-bb93-547329cdba6e",
    "skill_id": "0a83100f-4dfb-4d8f-aa48-5980d046cb37",
  },
  {
    "teacher_id": "0740143c-a00a-4173-a4cc-e951fda3515b",
    "skill_id": "3b848408-2280-4c3e-976a-4c51290a6e3e",
  },
  {
    "teacher_id": "ddd03ba5-f425-41da-bb93-547329cdba6e",
    "skill_id": "0a83100f-4dfb-4d8f-aa48-5980d046cb37",
  }

### Create EstudantSkills
POST http://localhost:3000/api/teacheSkills
Content-Type: application/json

  {
    "student_id": "283c5abf-ff3f-4450-849c-f715a38e4840",
    "hobbies_id": "320ddd71-3a77-4fd5-a2a6-61333b03edd8",
  },
  {
    "student_id": "b95e083c-785f-414a-b99b-913bf01d8072",
    "hobbies_id": "407a7280-d7d9-41ab-916d-840bf2220e79",
  },
  {
    "student_id": "283c5abf-ff3f-4450-849c-f715a38e4840",
    "hobbies_id": "320ddd71-3a77-4fd5-a2a6-61333b03edd8",
  }