http://localhost:3000/api/ping

###

POST http://localhost:3000/api/ping
Content-Type: application/json

{
  "name": "Isabele"
}

### Get all class
GET http://localhost:3000/api/class

### Create Class
POST http://localhost:3000/api/class
Content-Type: application/json

{
  "name": "Cruz",
  "startDate": "2021-01-25",
  "endDate": "2021-07-31",
  "module": "8"
}

### Update Class
PUT http://localhost:3000/api/class/c3ceec33-29b2-40d3-8cc9-3d3f16da9c33
Content-Type: application/json

{
  "name": "Epis",
  "startDate": "2021-01-25",
  "endDate": "2021-07-31",
  "module": "8"
}

### Delete Class
DELETE http://localhost:3000/api/class/94a0930c-a255-4051-9226-5b9f812c23fa
Content-Type: application/json

{
  "name": "Epis",
  "startDate": "2021-01-25",
  "endDate": "2021-07-31",
  "module": "8"
}


### Get all students
GET http://localhost:3000/api/student
### Get all Teachers
GET http://localhost:3000/api/teacher
### Get all Hobbies
GET http://localhost:3000/api/hobbies
### Get all Skills
GET http://localhost:3000/api/skills
### Get all TeacherSkills
GET http://localhost:3000/api/teacheSkills


### Get all studentsHobbies
GET http://localhost:3000/api/studentHobbies

### Create TeacherSkills
POST http://localhost:3000/api/teacheSkills
Content-Type: application/json

  {
    "teacher_id": "ce0b8452-00b3-47e1-b0b5-3a11d00079e2",
    "skill_id": "390be541-1d76-48db-a5d8-e4839460569a"
  }

### Create EstudantSkills
POST http://localhost:3000/api/studentHobbies
Content-Type: application/json

  {
    "student_id": "283c5abf-ff3f-4450-849c-f715a38e4840",
    "hobbies_id": "320ddd71-3a77-4fd5-a2a6-61333b03edd8",
  },


### Get search Hobbies
GET http://localhost:3000/api/hobbies/film

### Get all Teachers
GET http://localhost:3000/api/skills/re
