http://localhost:3000/ping

###

POST http://localhost:3000/ping
Content-Type: application/json

{
  "name": "Isabele"
}

### Get all student
GET http://localhost:3000/student

### Create student
POST http://localhost:3000/student
Content-Type: application/json

{
  "name": "Joaozinho da Silva",
  "email": "joaozinho@gmail.com",
  "birthDate": "1995-07-31",
  "class_id": "1378d99b-c882-4fb8-a5d6-91a6b15f4416"
}


### All Students in student By Name
GET http://localhost:3000/student/Cruz

### Update student
PUT http://localhost:3000/student/c3ceec33-29b2-40d3-8cc9-3d3f16da9c33
Content-Type: application/json

{
  "name": "Epis",
  "startDate": "2021-01-25",
  "endDate": "2021-07-31",
  "module": "8"
}

### Delete student
DELETE http://localhost:3000/student/c3ceec33-29b2-40d3-8cc9-3d3f16da9c33